apiVersion: v1
kind: Service
metadata:
  name: pythonapp
spec:
  selector:
    app: pythonapp
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30007
  type: NodePort

